
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PROGRAM = 10;
  public static final int DOSPUNTOS = 4;
  public static final int EOF = 0;
  public static final int VAR = 6;
  public static final int DOUBLE = 7;
  public static final int NUMERO = 2;
  public static final int ASSIGN = 3;
  public static final int error = 1;
  public static final int PUNTOYCOMA = 5;
  public static final int ENDPROGRAM = 11;
  public static final int END = 9;
  public static final int CHAR = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "ASSIGN",
  "DOSPUNTOS",
  "PUNTOYCOMA",
  "VAR",
  "DOUBLE",
  "CHAR",
  "END",
  "PROGRAM",
  "ENDPROGRAM"
  };
}

